create table note (
                      id bigint generated by default as identity primary key,
                      title varchar(200) not null,
                      content varchar(2000) not null
);